AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: >
  sam-app

  Sample SAM Template for sam-app

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 3

# More info about Parameters: https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/parameters-section-structure.html
Parameters:
  GitHubOAuthTokenSecretId:
    Type: String
    Default: "GitHubOAuthToken"
    Description: "The name of the secret that contains the GitHubOAuthToken value."
  GitHubOwner:
    Type: String
    Description: "GitHub username or organization that owns the repo."
  GitHubRepo:
    Type: String
    Description: "GitHub repo name."

Resources:
  HelloWorldFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: hello_world/
      Handler: app.lambda_handler
      Runtime: python3.8
      Events:
        HelloWorld:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /hello
            Method: get

  awssamcodebuildci:
    Type: AWS::Serverless::Application
    Properties:
      Location:
        ApplicationId: arn:aws:serverlessrepo:us-east-1:646794253159:applications/aws-sam-codebuild-ci
        SemanticVersion: 1.0.0
      Parameters:
        # AWS CodeBuild project compute type.
        # ComputeType: 'BUILD_GENERAL1_SMALL' # Uncomment to override default value
        # Environment type used by AWS CodeBuild. See the documentation for details (https://docs.aws.amazon.com/codebuild/latest/userguide/create-project.html#create-project-cli).
        # EnvironmentType: 'LINUX_CONTAINER' # Uncomment to override default value
        # OAuth token used by AWS CodeBuild to connect to GitHub
        GitHubOAuthToken: !Sub "{{resolve:secretsmanager:${GitHubOAuthTokenSecretId}}}"
        # GitHub username owning the repo
        GitHubOwner: !Ref GitHubOwner
        # GitHub repo name
        GitHubRepo: !Ref GitHubRepo

Outputs:
  # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
  # Find out more about other implicit resources you can reference within SAM
  # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
  HelloWorldApi:
    Description: "API Gateway endpoint URL for Prod stage for Hello World function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/hello/"
  HelloWorldFunction:
    Description: "Hello World Lambda Function ARN"
    Value: !GetAtt HelloWorldFunction.Arn
  HelloWorldFunctionIamRole:
    Description: "Implicit IAM Role created for Hello World function"
    Value: !GetAtt HelloWorldFunctionRole.Arn
